services:
  - type: worker
    name: telegram-stripe-bot
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python "bot.py"
    envVars:
      - key: API_TOKEN
        value: 8021681635:AAHUzI04WkaX7Qh6oGahtf864XucbbapcOI
      - key: STRIPE_SECRET_KEY
        value: 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
      - key: CHANNEL_ID
        value: -1002652142984
      - key: ADMIN_ID
        value: '1279721354'
